# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
locals {
  project_name = reverse(split("/", path.cwd))[0]
}

provider "aws" {
  region = var.aws_region
  default_tags {
    tags = {
      Organisation = var.organisation
      Environment  = var.env
      Managed_By   = "Terraform"
      Project      = reverse(split("/", "/Users/sagarmaurya/workspace/asmigar/create-nginx/infra/dev"))[2]
    }
  }
}
